### ISSUE TITLE
hbmenu version?

### ISSUE THREAD

**Issue by iCRON862** [zoogie/lasagnahax#1]
Will you update the exploit to can boot the Homebrew Menu for users who wan‘t install an cfw. Just for fun ^^ Or how to do it self?

**Comment by zoogie** [comment]
hbl otherapp needs the standard 0x101000 entrypoint to work. There's a lot of trouble at that address in Garfield Kart so I decided on using universal-otherapp since it's position independent (and for other reasons).

You can try to compile ninjhax-2x repo with -fPIE or address 0x190000 (the addr I ultimately used for GKart), but that would be quite a challenge. I don't have the time to tutor you through the process, sorry. Compiling that repo is something I dread to do myself.

https://github.com/zoogie/ninjhax2.x/tree/o3ds_newpayloads (old3ds)
https://github.com/zoogie/ninjhax2.x/tree/superto (new3ds)
